### ISSUE TITLE
redirect_uri_mismatch

### ISSUE THREAD

**Issue by renege** [FbF/Laravel-Youtube#1]
I get a redirect_uri_mismatch after trying to connect.

```
http://localhost.192.168.1.38.xip.io/youtube/public/youtube/public/youtube-upload-example/oauth2-callback
```

I'm having the same url as above as my redirect uri in the YT credentials.

Also tried adding some more info to the config, like; 

```
'redirect_uri' => 'youtube/public/youtube-upload-example/oauth2-callback', 
```

**Comment by neilcrookes** [comment]
The 2 URL paths need to match, this is what you've got:

youtube/public/youtube-upload-example/oauth2-callback
youtube/public/youtube/public/youtube-upload-example/oauth2-callback

I'm not sure if this is because you've configured it wrong or because you're running laravel in a subdirectory.

Can you try it in a virtual host rather than a subdirectory, after all, this is just to get the access token. After you've got it, you don't need this part of the code again.

Alternatively, feel free to adjust the helper code in the routes.php file to make it work for your set up, as I say, this is just some simple code that helps you get the access token, it should never be run in production. You can even recreate it in you own app/routes.php file, change the route paths and adjust the code to get it working with the way you've got Laravel installed.

Hope this helps, good luck.
